{% set name = "analphipy" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/analphipy-{{ version }}.tar.gz
  sha256: 8e11391cf06d14c492cc2725c15a01e3b825623f19af611a26c66f58a968b3cd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.2
    - setuptools-scm >=7.0
    - pip
  run:
    - python >=3.8
    - attrs
    - typing-extensions
    - numpy
    - scipy
    - docstring-inheritance
    - module-utilities >=0.6

test:
  imports:
    - analphipy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/usnistgov/analphipy
  summary: Utilities to perform stat mech analysis of pair potentials
  description: |
    `analphipy` is a python package to calculate metrics for classical models for
    pair potentials. It provides a simple and extendable api for pair potentials
    creation. Several routines to calculate metrics are included in the package.
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
